/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AgingBucket {
  'count' : bigint,
  'totalAmount' : number,
  'bucket' : string,
}
export interface CreateInvoiceRequest {
  'lineItems' : Array<LineItem>,
  'dueDate' : [] | [bigint],
  'invoiceType' : InvoiceType,
  'notes' : [] | [string],
  'partyId' : bigint,
}
export interface CreatePartyRequest {
  'gstNumber' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'partyType' : PartyType,
  'phone' : [] | [string],
}
export interface DashboardSummary {
  'totalSales' : number,
  'totalPurchases' : number,
  'outstandingReceivables' : number,
  'outstandingPayables' : number,
  'overdueInvoicesCount' : bigint,
}
export interface GSTINData {
  'tradeName' : string,
  'principalAddress' : string,
  'isActive' : boolean,
  'legalName' : string,
  'state' : string,
  'pincode' : string,
}
export interface InvoiceInfo {
  'id' : bigint,
  'status' : InvoiceStatus,
  'lineItems' : Array<LineItem>,
  'createdAt' : bigint,
  'dueDate' : [] | [bigint],
  'totalTax' : number,
  'amountPaid' : number,
  'grandTotal' : number,
  'updatedAt' : bigint,
  'invoiceNumber' : string,
  'invoiceType' : InvoiceType,
  'notes' : [] | [string],
  'totalDiscount' : number,
  'partyId' : bigint,
  'subtotal' : number,
}
export type InvoiceStatus = { 'cancelled' : null } |
  { 'paid' : null } |
  { 'sent' : null } |
  { 'overdue' : null } |
  { 'partiallyPaid' : null } |
  { 'draft' : null };
export type InvoiceType = { 'sales' : null } |
  { 'purchase' : null };
export interface LineItem {
  'taxPercent' : number,
  'rate' : number,
  'unit' : string,
  'itemName' : string,
  'discount' : number,
  'quantity' : number,
  'taxType' : TaxType,
}
export interface MonthlyFlow {
  'month' : bigint,
  'year' : bigint,
  'inflow' : number,
  'outflow' : number,
}
export interface PartyInfo {
  'id' : bigint,
  'gstNumber' : [] | [string],
  'name' : string,
  'createdAt' : bigint,
  'isActive' : boolean,
  'email' : [] | [string],
  'address' : [] | [string],
  'partyType' : PartyType,
  'phone' : [] | [string],
}
export type PartyType = { 'customer' : null } |
  { 'both' : null } |
  { 'vendor' : null };
export interface Payment {
  'id' : bigint,
  'method' : PaymentMethod,
  'invoiceId' : bigint,
  'recordedAt' : bigint,
  'notes' : [] | [string],
  'paymentDate' : bigint,
  'amount' : number,
}
export type PaymentMethod = { 'upi' : null } |
  { 'bank' : null } |
  { 'cash' : null } |
  { 'cheque' : null };
export interface RecordPaymentRequest {
  'method' : PaymentMethod,
  'invoiceId' : bigint,
  'notes' : [] | [string],
  'paymentDate' : bigint,
  'amount' : number,
}
export type TaxType = { 'igst' : null } |
  { 'none' : null } |
  { 'cgstSgst' : null };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UpdateInvoiceStatusRequest {
  'id' : bigint,
  'status' : InvoiceStatus,
}
export interface UpdatePartyRequest {
  'id' : bigint,
  'gstNumber' : [] | [string],
  'name' : string,
  'email' : [] | [string],
  'address' : [] | [string],
  'partyType' : PartyType,
  'phone' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelInvoice' : ActorMethod<[bigint], boolean>,
  'createInvoice' : ActorMethod<[CreateInvoiceRequest], InvoiceInfo>,
  'createParty' : ActorMethod<[CreatePartyRequest], PartyInfo>,
  'deactivateParty' : ActorMethod<[bigint], boolean>,
  'getAgingReport' : ActorMethod<[InvoiceType], Array<AgingBucket>>,
  'getCallerUserProfile' : ActorMethod<
    [],
    [] | [
      {
        'name' : string,
        'role' : { 'accountant' : null } |
          { 'owner' : null } |
          { 'viewer' : null },
      }
    ]
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDashboardSummary' : ActorMethod<[], DashboardSummary>,
  'getInvoice' : ActorMethod<[bigint], [] | [InvoiceInfo]>,
  'getMonthlyCashFlow' : ActorMethod<[bigint], Array<MonthlyFlow>>,
  'getParty' : ActorMethod<[bigint], [] | [PartyInfo]>,
  'getUserProfile' : ActorMethod<
    [Principal],
    [] | [
      {
        'name' : string,
        'role' : { 'accountant' : null } |
          { 'owner' : null } |
          { 'viewer' : null },
      }
    ]
  >,
  'gstTransform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listInvoices' : ActorMethod<
    [[] | [InvoiceType], [] | [InvoiceStatus]],
    Array<InvoiceInfo>
  >,
  'listParties' : ActorMethod<[[] | [PartyType]], Array<PartyInfo>>,
  'listPaymentsForInvoice' : ActorMethod<[bigint], Array<Payment>>,
  'lookupGSTIN' : ActorMethod<
    [string],
    { 'ok' : GSTINData } |
      { 'err' : string }
  >,
  'recordPayment' : ActorMethod<[RecordPaymentRequest], Payment>,
  'saveCallerUserProfile' : ActorMethod<
    [
      {
        'name' : string,
        'role' : { 'accountant' : null } |
          { 'owner' : null } |
          { 'viewer' : null },
      },
    ],
    undefined
  >,
  'updateInvoiceStatus' : ActorMethod<
    [UpdateInvoiceStatusRequest],
    [] | [InvoiceInfo]
  >,
  'updateParty' : ActorMethod<[UpdatePartyRequest], [] | [PartyInfo]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];