/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TaxType = IDL.Variant({
  'igst' : IDL.Null,
  'none' : IDL.Null,
  'cgstSgst' : IDL.Null,
});
export const LineItem = IDL.Record({
  'taxPercent' : IDL.Float64,
  'rate' : IDL.Float64,
  'unit' : IDL.Text,
  'itemName' : IDL.Text,
  'discount' : IDL.Float64,
  'quantity' : IDL.Float64,
  'taxType' : TaxType,
});
export const InvoiceType = IDL.Variant({
  'sales' : IDL.Null,
  'purchase' : IDL.Null,
});
export const CreateInvoiceRequest = IDL.Record({
  'lineItems' : IDL.Vec(LineItem),
  'dueDate' : IDL.Opt(IDL.Int),
  'invoiceType' : InvoiceType,
  'notes' : IDL.Opt(IDL.Text),
  'partyId' : IDL.Nat,
});
export const InvoiceStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'paid' : IDL.Null,
  'sent' : IDL.Null,
  'overdue' : IDL.Null,
  'partiallyPaid' : IDL.Null,
  'draft' : IDL.Null,
});
export const InvoiceInfo = IDL.Record({
  'id' : IDL.Nat,
  'status' : InvoiceStatus,
  'lineItems' : IDL.Vec(LineItem),
  'createdAt' : IDL.Int,
  'dueDate' : IDL.Opt(IDL.Int),
  'totalTax' : IDL.Float64,
  'amountPaid' : IDL.Float64,
  'grandTotal' : IDL.Float64,
  'updatedAt' : IDL.Int,
  'invoiceNumber' : IDL.Text,
  'invoiceType' : InvoiceType,
  'notes' : IDL.Opt(IDL.Text),
  'totalDiscount' : IDL.Float64,
  'partyId' : IDL.Nat,
  'subtotal' : IDL.Float64,
});
export const PartyType = IDL.Variant({
  'customer' : IDL.Null,
  'both' : IDL.Null,
  'vendor' : IDL.Null,
});
export const CreatePartyRequest = IDL.Record({
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'partyType' : PartyType,
  'phone' : IDL.Opt(IDL.Text),
});
export const PartyInfo = IDL.Record({
  'id' : IDL.Nat,
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'isActive' : IDL.Bool,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'partyType' : PartyType,
  'phone' : IDL.Opt(IDL.Text),
});
export const AgingBucket = IDL.Record({
  'count' : IDL.Nat,
  'totalAmount' : IDL.Float64,
  'bucket' : IDL.Text,
});
export const DashboardSummary = IDL.Record({
  'totalSales' : IDL.Float64,
  'totalPurchases' : IDL.Float64,
  'outstandingReceivables' : IDL.Float64,
  'outstandingPayables' : IDL.Float64,
  'overdueInvoicesCount' : IDL.Nat,
});
export const MonthlyFlow = IDL.Record({
  'month' : IDL.Nat,
  'year' : IDL.Int,
  'inflow' : IDL.Float64,
  'outflow' : IDL.Float64,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const PaymentMethod = IDL.Variant({
  'upi' : IDL.Null,
  'bank' : IDL.Null,
  'cash' : IDL.Null,
  'cheque' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : IDL.Nat,
  'method' : PaymentMethod,
  'invoiceId' : IDL.Nat,
  'recordedAt' : IDL.Int,
  'notes' : IDL.Opt(IDL.Text),
  'paymentDate' : IDL.Int,
  'amount' : IDL.Float64,
});
export const GSTINData = IDL.Record({
  'tradeName' : IDL.Text,
  'principalAddress' : IDL.Text,
  'isActive' : IDL.Bool,
  'legalName' : IDL.Text,
  'state' : IDL.Text,
  'pincode' : IDL.Text,
});
export const RecordPaymentRequest = IDL.Record({
  'method' : PaymentMethod,
  'invoiceId' : IDL.Nat,
  'notes' : IDL.Opt(IDL.Text),
  'paymentDate' : IDL.Int,
  'amount' : IDL.Float64,
});
export const UpdateInvoiceStatusRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : InvoiceStatus,
});
export const UpdatePartyRequest = IDL.Record({
  'id' : IDL.Nat,
  'gstNumber' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'address' : IDL.Opt(IDL.Text),
  'partyType' : PartyType,
  'phone' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelInvoice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'createInvoice' : IDL.Func([CreateInvoiceRequest], [InvoiceInfo], []),
  'createParty' : IDL.Func([CreatePartyRequest], [PartyInfo], []),
  'deactivateParty' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getAgingReport' : IDL.Func([InvoiceType], [IDL.Vec(AgingBucket)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [
        IDL.Opt(
          IDL.Record({
            'name' : IDL.Text,
            'role' : IDL.Variant({
              'accountant' : IDL.Null,
              'owner' : IDL.Null,
              'viewer' : IDL.Null,
            }),
          })
        ),
      ],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
  'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(InvoiceInfo)], ['query']),
  'getMonthlyCashFlow' : IDL.Func([IDL.Nat], [IDL.Vec(MonthlyFlow)], ['query']),
  'getParty' : IDL.Func([IDL.Nat], [IDL.Opt(PartyInfo)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [
        IDL.Opt(
          IDL.Record({
            'name' : IDL.Text,
            'role' : IDL.Variant({
              'accountant' : IDL.Null,
              'owner' : IDL.Null,
              'viewer' : IDL.Null,
            }),
          })
        ),
      ],
      ['query'],
    ),
  'gstTransform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listInvoices' : IDL.Func(
      [IDL.Opt(InvoiceType), IDL.Opt(InvoiceStatus)],
      [IDL.Vec(InvoiceInfo)],
      ['query'],
    ),
  'listParties' : IDL.Func(
      [IDL.Opt(PartyType)],
      [IDL.Vec(PartyInfo)],
      ['query'],
    ),
  'listPaymentsForInvoice' : IDL.Func([IDL.Nat], [IDL.Vec(Payment)], ['query']),
  'lookupGSTIN' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : GSTINData, 'err' : IDL.Text })],
      [],
    ),
  'recordPayment' : IDL.Func([RecordPaymentRequest], [Payment], []),
  'saveCallerUserProfile' : IDL.Func(
      [
        IDL.Record({
          'name' : IDL.Text,
          'role' : IDL.Variant({
            'accountant' : IDL.Null,
            'owner' : IDL.Null,
            'viewer' : IDL.Null,
          }),
        }),
      ],
      [],
      [],
    ),
  'updateInvoiceStatus' : IDL.Func(
      [UpdateInvoiceStatusRequest],
      [IDL.Opt(InvoiceInfo)],
      [],
    ),
  'updateParty' : IDL.Func([UpdatePartyRequest], [IDL.Opt(PartyInfo)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TaxType = IDL.Variant({
    'igst' : IDL.Null,
    'none' : IDL.Null,
    'cgstSgst' : IDL.Null,
  });
  const LineItem = IDL.Record({
    'taxPercent' : IDL.Float64,
    'rate' : IDL.Float64,
    'unit' : IDL.Text,
    'itemName' : IDL.Text,
    'discount' : IDL.Float64,
    'quantity' : IDL.Float64,
    'taxType' : TaxType,
  });
  const InvoiceType = IDL.Variant({
    'sales' : IDL.Null,
    'purchase' : IDL.Null,
  });
  const CreateInvoiceRequest = IDL.Record({
    'lineItems' : IDL.Vec(LineItem),
    'dueDate' : IDL.Opt(IDL.Int),
    'invoiceType' : InvoiceType,
    'notes' : IDL.Opt(IDL.Text),
    'partyId' : IDL.Nat,
  });
  const InvoiceStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'paid' : IDL.Null,
    'sent' : IDL.Null,
    'overdue' : IDL.Null,
    'partiallyPaid' : IDL.Null,
    'draft' : IDL.Null,
  });
  const InvoiceInfo = IDL.Record({
    'id' : IDL.Nat,
    'status' : InvoiceStatus,
    'lineItems' : IDL.Vec(LineItem),
    'createdAt' : IDL.Int,
    'dueDate' : IDL.Opt(IDL.Int),
    'totalTax' : IDL.Float64,
    'amountPaid' : IDL.Float64,
    'grandTotal' : IDL.Float64,
    'updatedAt' : IDL.Int,
    'invoiceNumber' : IDL.Text,
    'invoiceType' : InvoiceType,
    'notes' : IDL.Opt(IDL.Text),
    'totalDiscount' : IDL.Float64,
    'partyId' : IDL.Nat,
    'subtotal' : IDL.Float64,
  });
  const PartyType = IDL.Variant({
    'customer' : IDL.Null,
    'both' : IDL.Null,
    'vendor' : IDL.Null,
  });
  const CreatePartyRequest = IDL.Record({
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'partyType' : PartyType,
    'phone' : IDL.Opt(IDL.Text),
  });
  const PartyInfo = IDL.Record({
    'id' : IDL.Nat,
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'isActive' : IDL.Bool,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'partyType' : PartyType,
    'phone' : IDL.Opt(IDL.Text),
  });
  const AgingBucket = IDL.Record({
    'count' : IDL.Nat,
    'totalAmount' : IDL.Float64,
    'bucket' : IDL.Text,
  });
  const DashboardSummary = IDL.Record({
    'totalSales' : IDL.Float64,
    'totalPurchases' : IDL.Float64,
    'outstandingReceivables' : IDL.Float64,
    'outstandingPayables' : IDL.Float64,
    'overdueInvoicesCount' : IDL.Nat,
  });
  const MonthlyFlow = IDL.Record({
    'month' : IDL.Nat,
    'year' : IDL.Int,
    'inflow' : IDL.Float64,
    'outflow' : IDL.Float64,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const PaymentMethod = IDL.Variant({
    'upi' : IDL.Null,
    'bank' : IDL.Null,
    'cash' : IDL.Null,
    'cheque' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : IDL.Nat,
    'method' : PaymentMethod,
    'invoiceId' : IDL.Nat,
    'recordedAt' : IDL.Int,
    'notes' : IDL.Opt(IDL.Text),
    'paymentDate' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const GSTINData = IDL.Record({
    'tradeName' : IDL.Text,
    'principalAddress' : IDL.Text,
    'isActive' : IDL.Bool,
    'legalName' : IDL.Text,
    'state' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const RecordPaymentRequest = IDL.Record({
    'method' : PaymentMethod,
    'invoiceId' : IDL.Nat,
    'notes' : IDL.Opt(IDL.Text),
    'paymentDate' : IDL.Int,
    'amount' : IDL.Float64,
  });
  const UpdateInvoiceStatusRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : InvoiceStatus,
  });
  const UpdatePartyRequest = IDL.Record({
    'id' : IDL.Nat,
    'gstNumber' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'address' : IDL.Opt(IDL.Text),
    'partyType' : PartyType,
    'phone' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelInvoice' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'createInvoice' : IDL.Func([CreateInvoiceRequest], [InvoiceInfo], []),
    'createParty' : IDL.Func([CreatePartyRequest], [PartyInfo], []),
    'deactivateParty' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getAgingReport' : IDL.Func(
        [InvoiceType],
        [IDL.Vec(AgingBucket)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [],
        [
          IDL.Opt(
            IDL.Record({
              'name' : IDL.Text,
              'role' : IDL.Variant({
                'accountant' : IDL.Null,
                'owner' : IDL.Null,
                'viewer' : IDL.Null,
              }),
            })
          ),
        ],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDashboardSummary' : IDL.Func([], [DashboardSummary], ['query']),
    'getInvoice' : IDL.Func([IDL.Nat], [IDL.Opt(InvoiceInfo)], ['query']),
    'getMonthlyCashFlow' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MonthlyFlow)],
        ['query'],
      ),
    'getParty' : IDL.Func([IDL.Nat], [IDL.Opt(PartyInfo)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Opt(
            IDL.Record({
              'name' : IDL.Text,
              'role' : IDL.Variant({
                'accountant' : IDL.Null,
                'owner' : IDL.Null,
                'viewer' : IDL.Null,
              }),
            })
          ),
        ],
        ['query'],
      ),
    'gstTransform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listInvoices' : IDL.Func(
        [IDL.Opt(InvoiceType), IDL.Opt(InvoiceStatus)],
        [IDL.Vec(InvoiceInfo)],
        ['query'],
      ),
    'listParties' : IDL.Func(
        [IDL.Opt(PartyType)],
        [IDL.Vec(PartyInfo)],
        ['query'],
      ),
    'listPaymentsForInvoice' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'lookupGSTIN' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : GSTINData, 'err' : IDL.Text })],
        [],
      ),
    'recordPayment' : IDL.Func([RecordPaymentRequest], [Payment], []),
    'saveCallerUserProfile' : IDL.Func(
        [
          IDL.Record({
            'name' : IDL.Text,
            'role' : IDL.Variant({
              'accountant' : IDL.Null,
              'owner' : IDL.Null,
              'viewer' : IDL.Null,
            }),
          }),
        ],
        [],
        [],
      ),
    'updateInvoiceStatus' : IDL.Func(
        [UpdateInvoiceStatusRequest],
        [IDL.Opt(InvoiceInfo)],
        [],
      ),
    'updateParty' : IDL.Func([UpdatePartyRequest], [IDL.Opt(PartyInfo)], []),
  });
};

export const init = ({ IDL }) => { return []; };