/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface RecordPaymentRequest {
    method: PaymentMethod;
    invoiceId: bigint;
    notes?: string;
    paymentDate: bigint;
    amount: number;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface LineItem {
    taxPercent: number;
    rate: number;
    unit: string;
    itemName: string;
    discount: number;
    quantity: number;
    taxType: TaxType;
}
export interface InvoiceInfo {
    id: bigint;
    status: InvoiceStatus;
    lineItems: Array<LineItem>;
    createdAt: bigint;
    dueDate?: bigint;
    totalTax: number;
    amountPaid: number;
    grandTotal: number;
    updatedAt: bigint;
    invoiceNumber: string;
    invoiceType: InvoiceType;
    notes?: string;
    totalDiscount: number;
    partyId: bigint;
    subtotal: number;
}
export interface GSTINData {
    tradeName: string;
    principalAddress: string;
    isActive: boolean;
    legalName: string;
    state: string;
    pincode: string;
}
export interface AgingBucket {
    count: bigint;
    totalAmount: number;
    bucket: string;
}
export interface UpdatePartyRequest {
    id: bigint;
    gstNumber?: string;
    name: string;
    email?: string;
    address?: string;
    partyType: PartyType;
    phone?: string;
}
export interface MonthlyFlow {
    month: bigint;
    year: bigint;
    inflow: number;
    outflow: number;
}
export interface Payment {
    id: bigint;
    method: PaymentMethod;
    invoiceId: bigint;
    recordedAt: bigint;
    notes?: string;
    paymentDate: bigint;
    amount: number;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface DashboardSummary {
    totalSales: number;
    totalPurchases: number;
    outstandingReceivables: number;
    outstandingPayables: number;
    overdueInvoicesCount: bigint;
}
export interface CreateInvoiceRequest {
    lineItems: Array<LineItem>;
    dueDate?: bigint;
    invoiceType: InvoiceType;
    notes?: string;
    partyId: bigint;
}
export interface UpdateInvoiceStatusRequest {
    id: bigint;
    status: InvoiceStatus;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PartyInfo {
    id: bigint;
    gstNumber?: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    email?: string;
    address?: string;
    partyType: PartyType;
    phone?: string;
}
export interface CreatePartyRequest {
    gstNumber?: string;
    name: string;
    email?: string;
    address?: string;
    partyType: PartyType;
    phone?: string;
}
export enum InvoiceStatus {
    cancelled = "cancelled",
    paid = "paid",
    sent = "sent",
    overdue = "overdue",
    partiallyPaid = "partiallyPaid",
    draft = "draft"
}
export enum InvoiceType {
    sales = "sales",
    purchase = "purchase"
}
export enum PartyType {
    customer = "customer",
    both = "both",
    vendor = "vendor"
}
export enum PaymentMethod {
    upi = "upi",
    bank = "bank",
    cash = "cash",
    cheque = "cheque"
}
export enum TaxType {
    igst = "igst",
    none = "none",
    cgstSgst = "cgstSgst"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_accountant_owner_viewer {
    accountant = "accountant",
    owner = "owner",
    viewer = "viewer"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelInvoice(id: bigint): Promise<boolean>;
    createInvoice(req: CreateInvoiceRequest): Promise<InvoiceInfo>;
    createParty(req: CreatePartyRequest): Promise<PartyInfo>;
    deactivateParty(id: bigint): Promise<boolean>;
    getAgingReport(invoiceType: InvoiceType): Promise<Array<AgingBucket>>;
    getCallerUserProfile(): Promise<{
        name: string;
        role: Variant_accountant_owner_viewer;
    } | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDashboardSummary(): Promise<DashboardSummary>;
    getInvoice(id: bigint): Promise<InvoiceInfo | null>;
    getMonthlyCashFlow(months: bigint): Promise<Array<MonthlyFlow>>;
    getParty(id: bigint): Promise<PartyInfo | null>;
    getUserProfile(user: Principal): Promise<{
        name: string;
        role: Variant_accountant_owner_viewer;
    } | null>;
    gstTransform(raw: TransformationInput): Promise<TransformationOutput>;
    isCallerAdmin(): Promise<boolean>;
    listInvoices(invoiceType: InvoiceType | null, status: InvoiceStatus | null): Promise<Array<InvoiceInfo>>;
    listParties(partyType: PartyType | null): Promise<Array<PartyInfo>>;
    listPaymentsForInvoice(invoiceId: bigint): Promise<Array<Payment>>;
    lookupGSTIN(gstin: string): Promise<{
        __kind__: "ok";
        ok: GSTINData;
    } | {
        __kind__: "err";
        err: string;
    }>;
    recordPayment(req: RecordPaymentRequest): Promise<Payment>;
    saveCallerUserProfile(profile: {
        name: string;
        role: Variant_accountant_owner_viewer;
    }): Promise<void>;
    updateInvoiceStatus(req: UpdateInvoiceStatusRequest): Promise<InvoiceInfo | null>;
    updateParty(req: UpdatePartyRequest): Promise<PartyInfo | null>;
}
import type { CreateInvoiceRequest as _CreateInvoiceRequest, CreatePartyRequest as _CreatePartyRequest, GSTINData as _GSTINData, InvoiceInfo as _InvoiceInfo, InvoiceStatus as _InvoiceStatus, InvoiceType as _InvoiceType, LineItem as _LineItem, PartyInfo as _PartyInfo, PartyType as _PartyType, Payment as _Payment, PaymentMethod as _PaymentMethod, RecordPaymentRequest as _RecordPaymentRequest, TaxType as _TaxType, UpdateInvoiceStatusRequest as _UpdateInvoiceStatusRequest, UpdatePartyRequest as _UpdatePartyRequest, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelInvoice(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelInvoice(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelInvoice(arg0);
            return result;
        }
    }
    async createInvoice(arg0: CreateInvoiceRequest): Promise<InvoiceInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.createInvoice(to_candid_CreateInvoiceRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_InvoiceInfo_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createInvoice(to_candid_CreateInvoiceRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_InvoiceInfo_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createParty(arg0: CreatePartyRequest): Promise<PartyInfo> {
        if (this.processError) {
            try {
                const result = await this.actor.createParty(to_candid_CreatePartyRequest_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PartyInfo_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createParty(to_candid_CreatePartyRequest_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PartyInfo_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async deactivateParty(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateParty(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateParty(arg0);
            return result;
        }
    }
    async getAgingReport(arg0: InvoiceType): Promise<Array<AgingBucket>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAgingReport(to_candid_InvoiceType_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAgingReport(to_candid_InvoiceType_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<{
        name: string;
        role: Variant_accountant_owner_viewer;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardSummary(): Promise<DashboardSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardSummary();
            return result;
        }
    }
    async getInvoice(arg0: bigint): Promise<InvoiceInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getInvoice(arg0);
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getInvoice(arg0);
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyCashFlow(arg0: bigint): Promise<Array<MonthlyFlow>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyCashFlow(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyCashFlow(arg0);
            return result;
        }
    }
    async getParty(arg0: bigint): Promise<PartyInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getParty(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getParty(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<{
        name: string;
        role: Variant_accountant_owner_viewer;
    } | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async gstTransform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.gstTransform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.gstTransform(arg0);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listInvoices(arg0: InvoiceType | null, arg1: InvoiceStatus | null): Promise<Array<InvoiceInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listInvoices(to_candid_opt_n40(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listInvoices(to_candid_opt_n40(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n41(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async listParties(arg0: PartyType | null): Promise<Array<PartyInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listParties(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listParties(to_candid_opt_n45(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async listPaymentsForInvoice(arg0: bigint): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listPaymentsForInvoice(arg0);
                return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listPaymentsForInvoice(arg0);
            return from_candid_vec_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async lookupGSTIN(arg0: string): Promise<{
        __kind__: "ok";
        ok: GSTINData;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.lookupGSTIN(arg0);
                return from_candid_variant_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.lookupGSTIN(arg0);
            return from_candid_variant_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordPayment(arg0: RecordPaymentRequest): Promise<Payment> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(to_candid_RecordPaymentRequest_n53(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Payment_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(to_candid_RecordPaymentRequest_n53(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Payment_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: {
        name: string;
        role: Variant_accountant_owner_viewer;
    }): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_record_n57(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_record_n57(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateInvoiceStatus(arg0: UpdateInvoiceStatusRequest): Promise<InvoiceInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateInvoiceStatus(to_candid_UpdateInvoiceStatusRequest_n59(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateInvoiceStatus(to_candid_UpdateInvoiceStatusRequest_n59(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateParty(arg0: UpdatePartyRequest): Promise<PartyInfo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateParty(to_candid_UpdatePartyRequest_n61(this._uploadFile, this._downloadFile, arg0));
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateParty(to_candid_UpdatePartyRequest_n61(this._uploadFile, this._downloadFile, arg0));
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_InvoiceInfo_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceInfo): InvoiceInfo {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceStatus): InvoiceStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_InvoiceType_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _InvoiceType): InvoiceType {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_LineItem_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LineItem): LineItem {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_PartyInfo_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartyInfo): PartyInfo {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_PartyType_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PartyType): PartyType {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n49(_uploadFile, _downloadFile, value);
}
function from_candid_TaxType_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaxType): TaxType {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [{
        name: string;
        role: {
            accountant: null;
        } | {
            owner: null;
        } | {
            viewer: null;
        };
    }]): {
    name: string;
    role: Variant_accountant_owner_viewer;
} | null {
    return value.length === 0 ? null : from_candid_record_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_InvoiceInfo]): InvoiceInfo | null {
    return value.length === 0 ? null : from_candid_InvoiceInfo_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PartyInfo]): PartyInfo | null {
    return value.length === 0 ? null : from_candid_PartyInfo_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _InvoiceStatus;
    lineItems: Array<_LineItem>;
    createdAt: bigint;
    dueDate: [] | [bigint];
    totalTax: number;
    amountPaid: number;
    grandTotal: number;
    updatedAt: bigint;
    invoiceNumber: string;
    invoiceType: _InvoiceType;
    notes: [] | [string];
    totalDiscount: number;
    partyId: bigint;
    subtotal: number;
}): {
    id: bigint;
    status: InvoiceStatus;
    lineItems: Array<LineItem>;
    createdAt: bigint;
    dueDate?: bigint;
    totalTax: number;
    amountPaid: number;
    grandTotal: number;
    updatedAt: bigint;
    invoiceNumber: string;
    invoiceType: InvoiceType;
    notes?: string;
    totalDiscount: number;
    partyId: bigint;
    subtotal: number;
} {
    return {
        id: value.id,
        status: from_candid_InvoiceStatus_n14(_uploadFile, _downloadFile, value.status),
        lineItems: from_candid_vec_n16(_uploadFile, _downloadFile, value.lineItems),
        createdAt: value.createdAt,
        dueDate: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.dueDate)),
        totalTax: value.totalTax,
        amountPaid: value.amountPaid,
        grandTotal: value.grandTotal,
        updatedAt: value.updatedAt,
        invoiceNumber: value.invoiceNumber,
        invoiceType: from_candid_InvoiceType_n22(_uploadFile, _downloadFile, value.invoiceType),
        notes: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.notes)),
        totalDiscount: value.totalDiscount,
        partyId: value.partyId,
        subtotal: value.subtotal
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxPercent: number;
    rate: number;
    unit: string;
    itemName: string;
    discount: number;
    quantity: number;
    taxType: _TaxType;
}): {
    taxPercent: number;
    rate: number;
    unit: string;
    itemName: string;
    discount: number;
    quantity: number;
    taxType: TaxType;
} {
    return {
        taxPercent: value.taxPercent,
        rate: value.rate,
        unit: value.unit,
        itemName: value.itemName,
        discount: value.discount,
        quantity: value.quantity,
        taxType: from_candid_TaxType_n19(_uploadFile, _downloadFile, value.taxType)
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    gstNumber: [] | [string];
    name: string;
    createdAt: bigint;
    isActive: boolean;
    email: [] | [string];
    address: [] | [string];
    partyType: _PartyType;
    phone: [] | [string];
}): {
    id: bigint;
    gstNumber?: string;
    name: string;
    createdAt: bigint;
    isActive: boolean;
    email?: string;
    address?: string;
    partyType: PartyType;
    phone?: string;
} {
    return {
        id: value.id,
        gstNumber: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.gstNumber)),
        name: value.name,
        createdAt: value.createdAt,
        isActive: value.isActive,
        email: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.email)),
        address: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.address)),
        partyType: from_candid_PartyType_n31(_uploadFile, _downloadFile, value.partyType),
        phone: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.phone))
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: {
        accountant: null;
    } | {
        owner: null;
    } | {
        viewer: null;
    };
}): {
    name: string;
    role: Variant_accountant_owner_viewer;
} {
    return {
        name: value.name,
        role: from_candid_variant_n35(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_record_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    method: _PaymentMethod;
    invoiceId: bigint;
    recordedAt: bigint;
    notes: [] | [string];
    paymentDate: bigint;
    amount: number;
}): {
    id: bigint;
    method: PaymentMethod;
    invoiceId: bigint;
    recordedAt: bigint;
    notes?: string;
    paymentDate: bigint;
    amount: number;
} {
    return {
        id: value.id,
        method: from_candid_PaymentMethod_n50(_uploadFile, _downloadFile, value.method),
        invoiceId: value.invoiceId,
        recordedAt: value.recordedAt,
        notes: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.notes)),
        paymentDate: value.paymentDate,
        amount: value.amount
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    paid: null;
} | {
    sent: null;
} | {
    overdue: null;
} | {
    partiallyPaid: null;
} | {
    draft: null;
}): InvoiceStatus {
    return "cancelled" in value ? InvoiceStatus.cancelled : "paid" in value ? InvoiceStatus.paid : "sent" in value ? InvoiceStatus.sent : "overdue" in value ? InvoiceStatus.overdue : "partiallyPaid" in value ? InvoiceStatus.partiallyPaid : "draft" in value ? InvoiceStatus.draft : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    igst: null;
} | {
    none: null;
} | {
    cgstSgst: null;
}): TaxType {
    return "igst" in value ? TaxType.igst : "none" in value ? TaxType.none : "cgstSgst" in value ? TaxType.cgstSgst : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    sales: null;
} | {
    purchase: null;
}): InvoiceType {
    return "sales" in value ? InvoiceType.sales : "purchase" in value ? InvoiceType.purchase : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customer: null;
} | {
    both: null;
} | {
    vendor: null;
}): PartyType {
    return "customer" in value ? PartyType.customer : "both" in value ? PartyType.both : "vendor" in value ? PartyType.vendor : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    accountant: null;
} | {
    owner: null;
} | {
    viewer: null;
}): Variant_accountant_owner_viewer {
    return "accountant" in value ? Variant_accountant_owner_viewer.accountant : "owner" in value ? Variant_accountant_owner_viewer.owner : "viewer" in value ? Variant_accountant_owner_viewer.viewer : value;
}
function from_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    bank: null;
} | {
    cash: null;
} | {
    cheque: null;
}): PaymentMethod {
    return "upi" in value ? PaymentMethod.upi : "bank" in value ? PaymentMethod.bank : "cash" in value ? PaymentMethod.cash : "cheque" in value ? PaymentMethod.cheque : value;
}
function from_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _GSTINData;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: GSTINData;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_LineItem>): Array<LineItem> {
    return value.map((x)=>from_candid_LineItem_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_InvoiceInfo>): Array<InvoiceInfo> {
    return value.map((x)=>from_candid_InvoiceInfo_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PartyInfo>): Array<PartyInfo> {
    return value.map((x)=>from_candid_PartyInfo_n29(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n48(_uploadFile, _downloadFile, x));
}
function to_candid_CreateInvoiceRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateInvoiceRequest): _CreateInvoiceRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_CreatePartyRequest_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreatePartyRequest): _CreatePartyRequest {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceStatus_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): _InvoiceStatus {
    return to_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function to_candid_InvoiceType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceType): _InvoiceType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_LineItem_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LineItem): _LineItem {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_PartyType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyType): _PartyType {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_RecordPaymentRequest_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RecordPaymentRequest): _RecordPaymentRequest {
    return to_candid_record_n54(_uploadFile, _downloadFile, value);
}
function to_candid_TaxType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaxType): _TaxType {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateInvoiceStatusRequest_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateInvoiceStatusRequest): _UpdateInvoiceStatusRequest {
    return to_candid_record_n60(_uploadFile, _downloadFile, value);
}
function to_candid_UpdatePartyRequest_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdatePartyRequest): _UpdatePartyRequest {
    return to_candid_record_n62(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceType | null): [] | [_InvoiceType] {
    return value === null ? candid_none() : candid_some(to_candid_InvoiceType_n10(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus | null): [] | [_InvoiceStatus] {
    return value === null ? candid_none() : candid_some(to_candid_InvoiceStatus_n42(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyType | null): [] | [_PartyType] {
    return value === null ? candid_none() : candid_some(to_candid_PartyType_n27(_uploadFile, _downloadFile, value));
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gstNumber?: string;
    name: string;
    email?: string;
    address?: string;
    partyType: PartyType;
    phone?: string;
}): {
    gstNumber: [] | [string];
    name: string;
    email: [] | [string];
    address: [] | [string];
    partyType: _PartyType;
    phone: [] | [string];
} {
    return {
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        partyType: to_candid_PartyType_n27(_uploadFile, _downloadFile, value.partyType),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lineItems: Array<LineItem>;
    dueDate?: bigint;
    invoiceType: InvoiceType;
    notes?: string;
    partyId: bigint;
}): {
    lineItems: Array<_LineItem>;
    dueDate: [] | [bigint];
    invoiceType: _InvoiceType;
    notes: [] | [string];
    partyId: bigint;
} {
    return {
        lineItems: to_candid_vec_n5(_uploadFile, _downloadFile, value.lineItems),
        dueDate: value.dueDate ? candid_some(value.dueDate) : candid_none(),
        invoiceType: to_candid_InvoiceType_n10(_uploadFile, _downloadFile, value.invoiceType),
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        partyId: value.partyId
    };
}
function to_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    method: PaymentMethod;
    invoiceId: bigint;
    notes?: string;
    paymentDate: bigint;
    amount: number;
}): {
    method: _PaymentMethod;
    invoiceId: bigint;
    notes: [] | [string];
    paymentDate: bigint;
    amount: number;
} {
    return {
        method: to_candid_PaymentMethod_n55(_uploadFile, _downloadFile, value.method),
        invoiceId: value.invoiceId,
        notes: value.notes ? candid_some(value.notes) : candid_none(),
        paymentDate: value.paymentDate,
        amount: value.amount
    };
}
function to_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: Variant_accountant_owner_viewer;
}): {
    name: string;
    role: {
        accountant: null;
    } | {
        owner: null;
    } | {
        viewer: null;
    };
} {
    return {
        name: value.name,
        role: to_candid_variant_n58(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_record_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: InvoiceStatus;
}): {
    id: bigint;
    status: _InvoiceStatus;
} {
    return {
        id: value.id,
        status: to_candid_InvoiceStatus_n42(_uploadFile, _downloadFile, value.status)
    };
}
function to_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    gstNumber?: string;
    name: string;
    email?: string;
    address?: string;
    partyType: PartyType;
    phone?: string;
}): {
    id: bigint;
    gstNumber: [] | [string];
    name: string;
    email: [] | [string];
    address: [] | [string];
    partyType: _PartyType;
    phone: [] | [string];
} {
    return {
        id: value.id,
        gstNumber: value.gstNumber ? candid_some(value.gstNumber) : candid_none(),
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        partyType: to_candid_PartyType_n27(_uploadFile, _downloadFile, value.partyType),
        phone: value.phone ? candid_some(value.phone) : candid_none()
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    taxPercent: number;
    rate: number;
    unit: string;
    itemName: string;
    discount: number;
    quantity: number;
    taxType: TaxType;
}): {
    taxPercent: number;
    rate: number;
    unit: string;
    itemName: string;
    discount: number;
    quantity: number;
    taxType: _TaxType;
} {
    return {
        taxPercent: value.taxPercent,
        rate: value.rate,
        unit: value.unit,
        itemName: value.itemName,
        discount: value.discount,
        quantity: value.quantity,
        taxType: to_candid_TaxType_n8(_uploadFile, _downloadFile, value.taxType)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceType): {
    sales: null;
} | {
    purchase: null;
} {
    return value == InvoiceType.sales ? {
        sales: null
    } : value == InvoiceType.purchase ? {
        purchase: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PartyType): {
    customer: null;
} | {
    both: null;
} | {
    vendor: null;
} {
    return value == PartyType.customer ? {
        customer: null
    } : value == PartyType.both ? {
        both: null
    } : value == PartyType.vendor ? {
        vendor: null
    } : value;
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: InvoiceStatus): {
    cancelled: null;
} | {
    paid: null;
} | {
    sent: null;
} | {
    overdue: null;
} | {
    partiallyPaid: null;
} | {
    draft: null;
} {
    return value == InvoiceStatus.cancelled ? {
        cancelled: null
    } : value == InvoiceStatus.paid ? {
        paid: null
    } : value == InvoiceStatus.sent ? {
        sent: null
    } : value == InvoiceStatus.overdue ? {
        overdue: null
    } : value == InvoiceStatus.partiallyPaid ? {
        partiallyPaid: null
    } : value == InvoiceStatus.draft ? {
        draft: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    upi: null;
} | {
    bank: null;
} | {
    cash: null;
} | {
    cheque: null;
} {
    return value == PaymentMethod.upi ? {
        upi: null
    } : value == PaymentMethod.bank ? {
        bank: null
    } : value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.cheque ? {
        cheque: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_accountant_owner_viewer): {
    accountant: null;
} | {
    owner: null;
} | {
    viewer: null;
} {
    return value == Variant_accountant_owner_viewer.accountant ? {
        accountant: null
    } : value == Variant_accountant_owner_viewer.owner ? {
        owner: null
    } : value == Variant_accountant_owner_viewer.viewer ? {
        viewer: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TaxType): {
    igst: null;
} | {
    none: null;
} | {
    cgstSgst: null;
} {
    return value == TaxType.igst ? {
        igst: null
    } : value == TaxType.none ? {
        none: null
    } : value == TaxType.cgstSgst ? {
        cgstSgst: null
    } : value;
}
function to_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<LineItem>): Array<_LineItem> {
    return value.map((x)=>to_candid_LineItem_n6(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
